# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ecc897f431419945cc326eee3d958a76698eb3eb5dc303d4db2e59102b3a9a3ee05336dcfbbb2475baaa3fd4fc35048acbc07c23214c1caf10ad821ac3a6df2f

test:
  secret_key_base: e5f8691a12a366fe6895b1dc447bf94588d20d0fe1f8df1fe991e2ffc298fc38841c7473c1404a847199b915e48a08f2a87562fafb919af836cd4f1a0e3d6f07

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
